### ISSUE TITLE
Cannot dump geometry into schema.rb

### ISSUE THREAD

**Issue by ronna-s** [rgeo/activerecord-mysql2spatial-adapter#9] opened 2014-02-24 21:16 UTC
rake db:schema:dump generates error:
```ruby
# Could not dump table <NAME> because of following StandardError
# Unknown type 'geometry' for column 'borders'
```

**Comment by januszm** [comment] 2015-08-10 11:39
Resolved in #15

**Closed by januszm** 2015-08-10 11:39 UTC

**Comment by DhawalSawla** [comment] 2018-06-14 19:44
May I know how to solve this error?

**Comment by januszm** [comment] 2018-06-14 19:48
Are you using ActiveRecord 4.1? Because this gem is unfortunately compatible only with older ActiveRecord 4

**Comment by DhawalSawla** [comment] 2019-02-28 02:53
@januszm Sorry for the late reply. I am using ActiveRecord 4.2.
The issue is not while generating the schema file. The migration happens correctly and I see this error in the schema file.

# Could not dump table "offer_v2_locations" because of following StandardError
#   Unknown type 'geometry' for column 'geom'

Since the migration is done without any blocker, I ignore this.

But when I deploy to the codeship, the codeship does not create the offer_v2_locations model since this model is not created in the schema file.

I need to know how to create the model in the schema file so that on codeship, i can run my test cases.
